export const SET_MUSIC_LIST = 'SET_MUSIC_LIST'
export const SET_SONG_DETAIL = 'SET_SONG_DETAIL'
export const SHOW_PLAY = 'SHOW_PLAY'
export const SET_PLAYING = 'SET_PLAYING'
export const SET_PLAY_LIST = 'SET_PLAY_LIST'
export const SET_MODE = 'SET_MODE'
export const SET_CURRENT_INDEX = 'SET_CURRENT_INDEX'
