version: '2.0'

services:
  nginx:
    restart: always
    image: nginx:1.19.5-alpine
    ports:
      - 8080:80
    volumes:
#      - ./conf.d:/etc/nginx/conf.d
      - ./log:/var/log/nginx
#      - ./www:/var/www
      - ../dist:/usr/share/nginx/html
