version: '2.0'

services:
  node:
    image: node:12.13.0
    working_dir: /home/node/app
    volumes:
      - ../../source:/home/node/app
#      - /home/node/app/node_modules
    command: /bin/bash -c "npm install yarn -g && yarn install && yarn build"
  nginx:
    restart: always
    image: nginx:1.19.5-alpine
    ports:
      - 8001:80
    volumes:
      - ./log:/var/log/nginx
      - ../dist:/usr/share/nginx/html
